---
version: "2.0"

services:
  php:
    image: piyushch/skychallenge:1.0.0
    depends-on:
      - mysql
    env:
      - "MYSQL_HOST=mysql"
      - "MYSQL_USER="
      - "MYSQL_PASSWORD="
      - "MYSQL_DB=moe_db"
      - "dom=YOUR DOMAIN"
    expose:
      - port: 80
        as: 80
        to:
          - global: true
  mysql:
    image: mysql:5.7
    expose:
      - port: 3306
        as: 3306
        to:
          - service: php
      - port: 3306
        as: 3307
        to:
          - service: phpmyadmin
    env:
      - "MYSQL_ROOT_PASSWORD=rootpassword"
      - "MYSQL_USER="
      - "MYSQL_PASSWORD="
      - "MYSQL_DATABASE=moe_db"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends-on:
      - mysql
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - "PMA_HOST=mysql"
      - "PMA_PORT=3307"

profiles:
  compute:
    mysql:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    php:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    phpmyadmin:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi

  placement:
    westcoast:
      pricing:
        php:
          denom: uakt
          amount: 100
        mysql:
          denom: uakt
          amount: 100
        phpmyadmin:
          denom: uakt
          amount: 100

deployment:
  php:
    westcoast:
      profile: php
      count: 1
  mysql:
    westcoast:
      profile: mysql
      count: 1
  phpmyadmin:
    westcoast:
      profile: phpmyadmin
      count: 1
